Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -24,27 +24,77 @@ inputs:
   license:
     description: 'Provide the .NET Reactor license as either a file path or a base64-encoded string. If no license is defined .NET Reactor runs as demo version.'
     required: false
-  reactordir:
-    required: true
+  version:
+    description: 'Specify the .NET Reactor version to install. If unspecified, the latest version will be used.'
+    required: false
 runs:
   using: "composite"
   steps:
+    - name: Download and Extract .NET Reactor
+      run: |
+        os_name=$(echo ${{ runner.os }} | tr '[:upper:]' '[:lower:]')
+        
+        exe_name="dotNET_Reactor"
+        if [[ "${{ runner.os }}" == "Windows" ]]; then
+          exe_name="dotNET_Reactor.Console.exe"
+        fi
+        
+        download_url="https://raw.githubusercontent.com/eziriz/ReactorAction/main/versions/${os_name}_"
+        download_url_2="https://www.eziriz.com/downloads/versions/${os_name}_"
+        
+        if [ -n "${{ inputs.version }}" ]; then
+          version_formatted=$(echo "${{ inputs.version }}" | sed 's/\./_/g')
+          download_url="${download_url}${version_formatted}.zip"
+          download_url_2="${download_url_2}${version_formatted}.zip"
+          extract_dir="dotnet_reactor_${os_name}_${version_formatted}"
+        else
+          download_url="${download_url}latest.zip"
+          download_url_2="${download_url_2}latest.zip"
+          extract_dir="dotnet_reactor_${os_name}_latest"
+        fi
+        
+        if [ ! -f "$extract_dir/$exe_name" ]; then
+        
+          if ! curl --head --silent --fail $download_url; then
+            download_url=$download_url_2
+          fi
+
+          if ! curl --head --silent --fail $download_url; then
+            echo "The .NET Reactor version does not exist."
+            exit 1
+          fi
+        
+          echo "Downloading .NET Reactor ($download_url)..."
+          curl -L $download_url -o dotNetReactor.zip || { echo "Download failed"; exit 1; }
+          
+          echo "Unzipping .NET Reactor to ${extract_dir}..."
+          if [ "${{ runner.os }}" = "Windows" ]; then
+            7z x dotNetReactor.zip -o./${extract_dir} || { echo "Unzip failed"; exit 1; }
+          else
+            unzip dotNetReactor.zip -d ${extract_dir} || { echo "Unzip failed"; exit 1; }
+          fi
+        else
+          echo "${extract_dir}/${exe_name} already exists; skipping download."
+        fi
+        
+        echo "DOTNETREACTORROOT=$PWD/${extract_dir}" >> $GITHUB_ENV
+      shell: bash
     - name: Configure License
       run: |
             if [ -n "${{ inputs.license }}" ]; then
               if echo "${{ inputs.license }}" | grep -Eq '(\.license|\.v3lic)$'; then
-                cp "${{ inputs.license }}" ${{ inputs.reactordir }}/license.v3lic
+                cp "${{ inputs.license }}" ${{ env.DOTNETREACTORROOT }}/license.v3lic
               else
-                echo "${{ inputs.license }}" | base64 --decode > ${{ inputs.reactordir }}/license.v3lic
+                echo "${{ inputs.license }}" | base64 --decode > ${{ env.DOTNETREACTORROOT }}/license.v3lic
               fi
             fi
       shell: bash
     - name: Execute .NET Reactor for multiple files (in-place)
       run: |
-        command="${{ inputs.reactordir }}/dotNET_Reactor"
+        command="${{ env.DOTNETREACTORROOT }}/dotNET_Reactor"
 
         if [[ "${{ runner.os }}" == "Windows" ]]; then
-          command="${{ inputs.reactordir }}/dotNET_Reactor.Console.exe"
+          command="${{ env.DOTNETREACTORROOT }}/dotNET_Reactor.Console.exe"
         else
           chmod +x "$command"
         fi
